### ISSUE TITLE
Editor, github and atheneum are out of sync

### ISSUE THREAD

**Issue by matifreyre** [pdep-utn/mumuki-TP-funcional-entrega2-sabadoman#1]
Github is not being updated with the editor content. This guide has 8 exercises in the editor, but this repo is empty, and if you see it in Atheneum it has 3 exercises.

**Comment by matifreyre** [comment]
Everything was published, by the way.

**Comment by aguspina** [comment]
Fixed on https://github.com/mumuki/mumuki-bibliotheca/commit/d960862ac04d3b85c3367f07b364b8098e4a57d4
